name: testpjl
favicon: null
layout_spectrum: 0
typography_spectrum: 0.24071
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#211f20'
    - '#414f4e'
    - '#606d53'
    - '#94988a'
    - '#f8f9f0'
  brandStrength: 0.5
  lightness: 0.375
  saturation: 0.5
  rhythmicContrast: 1
purpose: []
