name: testpjl
favicon: null
layout_spectrum: 0.3808770510368049
typography_spectrum: 0.313215620117262
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.13512854394502938
  lightness: 0.23806253704242408
  saturation: 0.12137763667851686
  rhythmicContrast: 0.3378926033619791
purpose: []
