name: testpjl
favicon: null
layout_spectrum: 0.75515
typography_spectrum: 0.24071
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#211f20'
    - '#414f4e'
    - '#606d53'
    - '#94988a'
    - '#f8f9f0'
  brandStrength: 0.13512854394502938
  lightness: 0.23806253704242408
  saturation: 0.12137763667851686
  rhythmicContrast: 0.3378926033619791
purpose: []
